language: node_js

node_js:
 - "0.8"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#talkilla"
    use_notice: false
    skip_join: false
  email:
    - talkilla-travis-results@mozilla.com
