language: node_js

node_js:
  - "0.8"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#talkilla"
    use_notice: false
    skip_join: false
  email:
    - talkilla-travis-results@mozilla.com

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then
      echo "This is a pull request, not requesting deployment";
      exit 0;
    fi
  - echo "Requesting deployment"
  - wget -q -O - http://54.235.119.32/check
